   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('SOLR-4459','The Replication index move rather than copy optimization doesnt kick in when using NRTCachingDirectory or the rate limiting feature.',(to_timestamp('15/02/13 05:00:00','dd-mm-yy hh24:mi:ss')),(to_timestamp('10/05/13 11:33:00','dd-mm-yy hh24:mi:ss')), (to_timestamp('16/02/13 02:27:00','dd-mm-yy hh24:mi:ss')), 'Bug', 'Closed', 'Major', 'Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('SOLR-5098','Support adding field types to managed schema',(to_timestamp('31/07/13 21:27', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('10/09/14 20:08', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('10/09/14 17:35', 'dd-mm-yy hh24:mi:ss')),'Sub-task', 'Resolved', 'Minor', 'Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('SOLR-2345','geodist support for RPT',(to_timestamp('16/07/13 18:18', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('24/07/13 18:26 ', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('24/07/13 18:26', 'dd-mm-yy hh24:mi:ss')),'New Feature','Closed','Major','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('SOLR-4916','Add support to write and read Solr index files and transaction log files to and from HDFS.',(to_timestamp('22/07/13 20:56', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('25/07/13 01:52', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('25/07/13 01:52', 'dd-mm-yy hh24:mi:ss')),'Sub-task','Resolved','Major','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('SOLR-2654','Directorys used by a SolrCore are now closed when they are no longer used.',(to_timestamp('20/09/12 18:47', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('22/03/13 16:29', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('01/10/12 17:06', 'dd-mm-yy hh24:mi:ss')),'Bug','Closed','Minor','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-5518' ,'minor hunspell optimizations',(to_timestamp('11/03/14 03:36', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('12/03/14 13:50', 'dd-mm-yy hh24:mi:ss')), null, 'Improvement','Open','Major', 'Unresolved');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-2510','add more tests, fix bugs found by test where misconfigured factories wouldnt error out until runtime',(to_timestamp('23/06/10 14:08', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('10/05/13 11:44', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('25/07/12, 'dd-mm-yy hh24:mi:ss')) 19:04','Task','Closed','Major','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-4984','Fix ThaiWordFilter, smartcn WordTokenFilter',(to_timestamp('07/05/13 17:13' , 'dd-mm-yy hh24:mi:ss')), (to_timestamp('28/04/14 00:25', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('21/03/14 01:05', 'dd-mm-yy hh24:mi:ss')),'Bug','Closed','Major','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-3069' ,'Lucene should have an entirely memory resident term dictionary',(to_timestamp('29/08/13 18:32', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('05/10/13 11:19', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('29/08/13 18:42', 'dd-mm-yy hh24:mi:ss')),'Bug','Closed','Major','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-3753' ,'Restructure the Lucene build system',(to_timestamp('05/02/12 23:42', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('10/05/13 11:44', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('15/02/12 22:30', 'dd-mm-yy hh24:mi:ss')),'Improvement','Closed','Minor','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-5969' ,'move old postings back compat to backward-codecs, cleanup PBF related stuff, add segment headers, etc',(to_timestamp('06/10/14 10:05', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('06/10/14 23:11', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('06/10/14 23:11', 'dd-mm-yy hh24:mi:ss')),'Improvement','Resolved','Major','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-4236' ,'move all crazies into one place',(to_timestamp('10/12/12 14:52', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('30/01/14 17:01', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('14/03/13 21:20', 'dd-mm-yy hh24:mi:ss')),'Bug','Closed','Major','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-5166' ,'clear most nocommits, move ord/rord to solr (and speed them up), nuke old purging stuff',(to_timestamp('12/08/13 08:20', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('14/05/14 06:51' , 'dd-mm-yy hh24:mi:ss')),(to_timestamp('15/08/13 18:05', 'dd-mm-yy hh24:mi:ss')), 'Bug','Closed','Major','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-4848' ,'Use Java 7 NIO2-FileChannel instead of RandomAccessFile for NIOFSDirectory and MMapDirectory',(to_timestamp('20/03/13 19:01', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('23/02/14 12:08', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('29/03/13 17:48', 'dd-mm-yy hh24:mi:ss')), 'Improvement', 'Resolved', 'Major', 'Wont Fix');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-3867' ,'Refactor RamUsageEstimator. CHANGES.txt will be added once backported to 3.x.',(to_timestamp('19/03/12 22:52', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('10/05/13 11:44', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('19/03/12 23:23', 'dd-mm-yy hh24:mi:ss')), 'Bug', 'Closed', 'Major', 'Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-5569' ,'*AtomicReader/AtomicReaderContext have been renamed to *LeafReader-LeafReaderContext',(to_timestamp('03/04/14 19:39', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('24/09/14 10:30', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('24/09/14 10:30', 'dd-mm-yy hh24:mi:ss')), 'Improvement', 'Resolved','Blocker','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-4975' ,'Add Replication module to Lucene',(to_timestamp('06/05/13 09:25', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('23/07/13 19:37', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('07/05/13 06:54', 'dd-mm-yy hh24:mi:ss')),'Improvement','Closed','Major','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-4208' ,'makeQuery return ConstantScoreQuery, standardize makeDistanceValueSource behavior',(to_timestamp('27/06/12 12:27', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('21/09/12 05:59', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('21/09/12 05:59', 'dd-mm-yy hh24:mi:ss')), 'Bug','Resolved','Major','Wont Fix');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-5214' ,'add FreeTextSuggester',(to_timestamp('15/09/13 14:36', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('02/10/13 19:00', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('02/10/13 16:31', 'dd-mm-yy hh24:mi:ss')),'Improvement','Resolved','Major','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-4752' ,'Preliminaries:- move useful assert*Equals from TestDuelingCodecs to LuceneTestCase,- rename sort to wrap in SortingAtomicReader to better suggest that the returned reader is a view.',(to_timestamp('20/03/13 16:26', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('10/05/13 11:33', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('21/03/13 17:14', 'dd-mm-yy hh24:mi:ss')),'Improvement','Closed','Minor','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-3930' ,'nuke jars from source tree and use ivy',(to_timestamp('27/03/12 23:17', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('10/05/13 11:42', 'dd-mm-yy hh24:mi:ss')), (to_timestamp('02/04/12 21:58', 'dd-mm-yy hh24:mi:ss')),'Task','Closed','Blocker','Fixed');

   INSERT INTO lusene_found_issues (bugid, summary, creationDate, commitedDate, resolvedDate, issueClassification, status, priority, resolution) values ('LUCENE-5399' ,'current state',(to_timestamp('14/01/14 10:31', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('16/03/14 13:02', 'dd-mm-yy hh24:mi:ss')),(to_timestamp('16/01/14 19:02', 'dd-mm-yy hh24:mi:ss')),'Bug','Closed','Major','Fixed');
